#!/usr/bin/env bash
# One-time Cloudflare Tunnel setup for shakur.verxyl.com — CLI flow.
#
# Prerequisite (interactive, run it yourself first):
#   cloudflared tunnel login
# It prints a URL; open it in your browser, pick the verxyl.com zone, done.
# That writes ~/.cloudflared/cert.pem, which authorizes everything below.
#
# Then this script is fully non-interactive:
#   bash scripts/setup-tunnel.sh
set -euo pipefail

TUNNEL_NAME="shakur"
HOSTNAME="shakur.verxyl.com"
ORIGIN="http://web:3000"

CF_DIR="${HOME}/.cloudflared"
OUT_DIR="$(cd "$(dirname "$0")/.." && pwd)/cloudflared"

if [[ ! -f "${CF_DIR}/cert.pem" ]]; then
  echo "✗ ${CF_DIR}/cert.pem not found." >&2
  echo "  Run 'cloudflared tunnel login' first (it opens a browser link)." >&2
  exit 1
fi

# --- 1. Create the tunnel (idempotent) ---------------------------------------
if cloudflared tunnel list --output json | grep -q "\"name\":\"${TUNNEL_NAME}\""; then
  echo "• Tunnel '${TUNNEL_NAME}' already exists — reusing it."
else
  cloudflared tunnel create "${TUNNEL_NAME}"
fi

TUNNEL_ID="$(cloudflared tunnel list --output json \
  | python3 -c "import json,sys; print(next(t['id'] for t in json.load(sys.stdin) if t['name']=='${TUNNEL_NAME}'))")"
echo "• Tunnel ID: ${TUNNEL_ID}"

# --- 2. Point DNS at it (idempotent: --overwrite-dns) -------------------------
cloudflared tunnel route dns --overwrite-dns "${TUNNEL_NAME}" "${HOSTNAME}"
echo "• DNS: ${HOSTNAME} -> ${TUNNEL_ID}.cfargotunnel.com"

# --- 3. Bundle credentials + config for the container -------------------------
mkdir -p "${OUT_DIR}"
cp "${CF_DIR}/${TUNNEL_ID}.json" "${OUT_DIR}/credentials.json"
chmod 600 "${OUT_DIR}/credentials.json"

cat > "${OUT_DIR}/config.yml" <<EOF
# Generated by scripts/setup-tunnel.sh — do not commit this directory.
tunnel: ${TUNNEL_ID}
credentials-file: /etc/cloudflared/credentials.json

ingress:
  - hostname: ${HOSTNAME}
    service: ${ORIGIN}
  # Required catch-all: anything not matching the hostname above gets a 404.
  - service: http_status:404
EOF

echo "• Wrote ${OUT_DIR}/config.yml and credentials.json"
echo
echo "✓ Done. Start (or restart) the stack:"
echo "    docker compose up -d --build"
